### ISSUE TITLE
Missing left colon on completion

### ISSUE THREAD

**Issue by barnumbirr** [akatopo/GithubEmoji#12]
Hello,

currently running ST4 (build 4112 on Win10), default `GithubEmoji` config.
When I `TAB` or `ENTER` to autocomplete an emoji name, the left colon gets trimmed and I end up with `pizza:`.
Let me know if I managed to make myself clear enough, if not I'll try to get a screencast.

Cheers.

**Comment by eugenesvk** [comment]
FYI you may wish to try [my fork's ST4 branch](https://github.com/eugenesvk/GithubEmoji/tree/ST4) that should fix this before the changes are merged here (check [the changelog](https://github.com/eugenesvk/GithubEmoji/blob/ST4/messages/1.3.0.md) for more details if you have your own emoji list in the settings)

**Comment by akatopo** [comment]
Fixed in #14
