### ISSUE TITLE
Remove extra : when using autocomplete dropdown

### ISSUE THREAD

**Issue by dhulihan** [akatopo/GithubEmoji#2]
I use the autocomplete dropdown quite a bit (by turning on the `auto_complete_selector` setting). When I use it to grab a GithubEmoji, an extra `:` remains.

![feb 22 2016 09 17](https://cloud.githubusercontent.com/assets/519728/13224331/38f5b1a6-d945-11e5-8567-87fd596c6a74.gif)

This package is awesome btw

**Comment by akatopo** [comment]
Thanks for your kind words :smile_cat:

Release 1.1.2 should fix your issue, it will be pushed to package control soon. If you still have issues please share.
