### ISSUE TITLE
No completion in COMMIT_EDITMSG when using Sublime Git

### ISSUE THREAD

**Issue by sebz** [akatopo/GithubEmoji#3]
Hi @akatopo, I'm using https://github.com/SublimeGit/SublimeGit and don't have any completion while editing commit messages. It's working perfectly in Markdown files.

![image](https://cloud.githubusercontent.com/assets/590088/19013112/8a4e880c-87c8-11e6-8fa6-d183db59f84a.png)

**Comment by akatopo** [comment]
Hi @sebz, thanks for reporting this.

Completions should work if you add `text.git-commit` into the `emojiScopes` array in your user settings (`Preferences > Package Settings > GithubEmoji > Settings – User`).

ex.

``` json
{
  "emojiScopes": [
    "text.html.markdown",
    "text.git-commit"
  ]
}
```

I'll add this scope in the default settings so in the future there'll be no need to add this. Let me know if you still got issues

**Comment by sebz** [comment]
Great! Just tested it, indeed it works better :smile: 
In fact, I misread the documentation and thought it should work out of the box.

Thanks and awesome work !
